#!/usr/bin/python3

import argparse
import json
import pickle

from keras import optimizers
from keras.callbacks import ModelCheckpoint
from keras.callbacks import TensorBoard
from keras.callbacks import LearningRateScheduler
from keras.utils import multi_gpu_model
from keras.models import load_model
from keras import backend as K
import tensorflow as tf

from utils import PolyDecay
from utils import MapillaryGenerator
import model

parser = argparse.ArgumentParser()
parser.add_argument('--batch_size', type=int, default=16, help='input batch size')
parser.add_argument('--image_width', type=int, default=640, help='the input image width')
parser.add_argument('--image_height', type=int, default=320, help='the input image height')
parser.add_argument('--lr', type=float, default=0.01, help='learning rate of the optimizer')
parser.add_argument('--decay', type=float, default=0.9, help='learning rate decay (per epoch)')
parser.add_argument('--n_epochs', type=int, default=100, help='number of epochs to train for')
parser.add_argument('--n_gpu', type=int, default=1, help='number of GPUs to use')
parser.add_argument('--n_cpu', type=int, default=8, help='number of CPU threads to use during data generation')
parser.add_argument('--checkpoint', type=str, default=None, help='path to model checkpoint to resume training')
parser.add_argument('--epoch', type=int, default=0, help='epoch to start training')
parser.add_argument('-r', '--remap', action='store_true')
opt = parser.parse_args()

print(opt)

#### Train ####

# Workaround to forbid tensorflow from crashing the gpu
config = K.tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = K.tf.Session(config=config)
K.set_session(sess)

# Callbacks
checkpoint = ModelCheckpoint('output/weights.{epoch:03d}-{val_conv6_cls_categorical_accuracy:.3f}.h5', monitor='val_conv6_cls_categorical_accuracy', mode='max')
tensorboard = TensorBoard(batch_size=opt.batch_size)
lr_decay = LearningRateScheduler(PolyDecay(opt.lr, opt.decay, opt.n_epochs).scheduler)

# Generators
if opt.remap:
    remap = {13: [7, 8, 9, 10, 11, 12, 13, 14, 15],             # Driveable Area
             24: [23, 24],                                      # Lane Lines
             55: [52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62],  # Vehicles
             27: [27]}                                          # Sky
    n_classes = len(remap) + 1
    with open('datasets/mapillary/config.json') as config_file:
        config = json.load(config_file)
    labels = config['labels']
    custom_labels = [{'color':[0,0,0]}]
    for k,v in remap.items():
        custom_labels.append({'color':labels[k]['color']})
    with open('custom_labels.pkl', 'wb') as lfile:
        pickle.dump(custom_labels, lfile)
    with open('remap.pkl', 'wb') as rfile:
        pickle.dump(remap, rfile)
else:
    remap = None
    n_classes = 66

train_generator = MapillaryGenerator(batch_size=opt.batch_size, crop_shape=(opt.image_width, opt.image_height), remap=remap)
val_generator = MapillaryGenerator(mode='validation', batch_size=opt.batch_size, crop_shape=None, resize_shape=(opt.image_width, opt.image_height), remap=remap)

# Optimizer
optim = optimizers.SGD(lr=opt.lr, momentum=0.9)

# Model
if opt.checkpoint:
    net = load_model(opt.checkpoint, custom_objects={'tf':tf})
else:
    net = model.build_bn(opt.image_width, opt.image_height, n_classes, train=True)
if opt.n_gpu > 1:
    net = multi_gpu_model(net, opt.n_gpu)

def mean_iou(y_true, y_pred):
   score, up_opt = tf.metrics.mean_iou(y_true, y_pred, n_classes)
   K.get_session().run(tf.local_variables_initializer())
   with tf.control_dependencies([up_opt]):
       score = tf.identity(score)
   return score

# Training
net.compile(optim, 'categorical_crossentropy', loss_weights=[1.0, 0.4, 0.16], metrics=['categorical_accuracy', mean_iou])
net.fit_generator(train_generator, len(train_generator), opt.n_epochs, callbacks=[checkpoint, tensorboard, lr_decay], 
                    validation_data=val_generator, validation_steps=len(val_generator), workers=opt.n_cpu, 
                    use_multiprocessing=False, shuffle=True, max_queue_size=10, initial_epoch=opt.epoch)                   
###############
